# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "dotfiles/monochrome"

[settings]
# An array of toml files paths containing the variables to inject in your templatize dotfiles
# You can have multiple var files as long as variable names does not colide. 
vars = [ "vars.toml" ]

# An array of post install shell commands
hooks = [ "bspc wm -r", "pkill -USR1 -x sxhkd"]

[settings.dots]
# A dot entry representing a symlink, `source` is relative to `dotfiles_dir` 
# and `target` shall be relative to $HOME directory or absolute.
bspwm = { source = "config/bspwm/", target = ".config/bspwm" } 
gtk2 = { source = "config/gtk-2.0" , target = ".config/gtk-2.0" }
gtk3 = { source = "config/gtk-3.0", target = ".config/gtk-3.0" }
kitty = { source = "config/kitty", target = ".config/kitty" }
polybar = { source = "config/polybar", target = ".config/polybar" }
picom = { source = "config/picom.conf", target = ".config/picom.conf" }
gtkrc = { source = "config/gtkrc", target = ".config/gtkrc" }
gtkrc2 = { source = "config/gtkrc-2.0", target = ".config/gtkrc-2.0" }
sxhkd = { source = "config/sxhkd", target = ".config/sxhkd" }
rofi = { source = "config/rofi", target = ".config/rofi" }

themes = { source = "themes", target = ".themes" }
icons = { source = "icons", target=".icons" } 
img = { source = "img", target = "img" }
tmux = { source = "tmux.conf", target = ".tmux.conf" }

